name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Maven
      uses: stCarolas/setup-maven@v1
      with:
        maven-version: 3.5.4
